version: '3'

services:
  build:
    build: .
    command: make all
    working_dir: /main
    volumes:
      - './whitepaper:/main'
  shell:
    build: .
    command: bash
    working_dir: /main
    volumes:
      - './whitepaper:/main'
